import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { HttpAgent } from '@ag-ui/client';
import type { AgentSubscriber, Message } from '@ag-ui/client';
import { useQueryClient } from '@tanstack/react-query';
import { PRAGNA_BASE_URL } from '@/constants/api';
import { useAuthStore } from '@/presentation/store/authStore';
import { logger } from '@/infrastructure/logging/logger';

// First sidebar refresh fires immediately on RUN_FINISHED so the user
// sees the new conversation appear right away (title may still be null).
// The backend's auto-title flow is fire-and-forget after persistence and
// usually completes within 1-2s of the assistant response ending — a
// second invalidation after this delay catches the title once it lands.
// Tuned conservatively (3s) to ride past a slow first-turn title-gen
// without making the sidebar feel laggy.
const AUTO_TITLE_REFRESH_DELAY_MS = 3000;

/** A tool call rendered inline under an assistant turn. */
export interface ChatToolCall {
  id: string;
  name: string;
  /** Cumulative argument JSON snippet as the LLM streams it. */
  argsBuffer: string;
  /** Final parsed args once the call completes; ``undefined`` while streaming. */
  args?: Record<string, unknown>;
  /** Tool result, if the server emitted a ToolCallResultEvent. */
  result?: string;
  /** True once we've seen the matching ToolCallEndEvent. */
  complete: boolean;
}

/** UI-shaped message — the canonical state the chat view renders. */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'tool' | 'system';
  content: string;
  /** Assistant-only: any tool calls the LLM emitted during the turn. */
  toolCalls?: ChatToolCall[];
}

export type ChatStatus = 'idle' | 'running' | 'error';

export interface ChatSessionApi {
  /** Current turn state. Reflects the underlying ``HttpAgent.messages`` 1:1. */
  messages: ChatMessage[];
  /** Current run status. ``error`` flips back to ``idle`` on the next send. */
  status: ChatStatus;
  /** Last error message when ``status === 'error'``; ``null`` otherwise. */
  error: string | null;
  /**
   * R7.1#3 follow-up — latest live progress label from the agent.
   * Backed by the LangChain ``on_progress`` custom event emitted from
   * every ``BaseAgentNode.__call__`` on the BE. ``null`` between runs
   * and when the latest event hasn't carried a label.
   *
   * Last-wins: in a parallel-agents flow, the most recent emit
   * overwrites previous labels (per the R7.1#3 follow-up design call —
   * matches Cursor / ChatGPT behaviour, simpler than stacking).
   *
   * Cleared on every transition out of ``running`` (RunFinalized /
   * RunError) so the thinking strip disappears the moment the run
   * settles.
   */
  progressLabel: string | null;
  /**
   * Append a user turn and run the agent. No-op while a run is in flight.
   * R5: ``attachmentIds`` is the list of staged attachment IDs that the
   * backend has already received; they ride along in
   * ``forwarded_props.attachment_ids`` so the pragna route can resolve
   * + inject the bytes before invoking the LLM.
   */
  send: (text: string, attachmentIds?: string[]) => void;
  /**
   * R4 #1. Same as :func:`send` but adds ``?user_model_id=<modelId>`` to
   * the pragna URL for this single run, so the default agent runs against
   * the chosen model instead of the conversation's persisted preference.
   * The conversation's own user_model_id is NOT updated — the next plain
   * :func:`send` falls back to the user's preference automatically.
   */
  sendWithModel: (text: string, userModelId: string) => void;
  /**
   * Landing → first-send variant. Like :func:`send`, but mutates the
   * pragna URL with ``?user_model_id=`` and ``?thinking_enabled=``
   * query params reconstructed from the landing's picker state. The
   * backend's pragna route reads these on auto-create and stamps the
   * conversation row's columns to match — without this, the first turn
   * would use server defaults regardless of what the user picked on
   * the landing.
   *
   * No-op for empty / running states. ``attachmentIds`` carried through
   * the same way :func:`send` carries them.
   */
  sendWithOverrides: (
    text: string,
    opts: {
      attachmentIds?: string[];
      userModelId?: string;
      thinkingEnabled?: boolean;
    },
  ) => void;
  /** Abort the current run. Safe to call when no run is active. */
  stop: () => void;
}

export interface UseChatSessionOptions {
  /**
   * Pinning a stable ``thread_id`` lets the backend recognise this as a
   * resumed conversation. New chats pass a fresh UUID generated by the
   * view; resumed chats pass ``conversation.id``. Changes recreate the
   * underlying ``HttpAgent``.
   */
  threadId?: string;
  /**
   * Seed messages to hydrate the agent with on mount — used on resume
   * (the persisted history is fetched via :func:`useConversationMessages`
   * and passed in here). The first turn after mount appends to this
   * list rather than replacing it.
   *
   * The ``AgentConfig`` field is named ``initialMessages``; we keep the
   * same name for clarity.
   */
  initialMessages?: Message[];
}

/**
 * Stateful hook that wires a single :class:`HttpAgent` to React state.
 *
 * Lifetime:
 *   - One HttpAgent per ``(agentName, accessToken, threadId)`` triple,
 *     recreated on any of those changing. Reusing the same ``threadId``
 *     across requests is what makes "resume conversation" work.
 *   - The subscriber is installed once at agent creation and mirrors
 *     ``HttpAgent.messages`` into local state on every event.
 *
 * Concurrency: ``send`` is a no-op while a run is in flight. The user must
 * either wait or call ``stop`` first. ``stop`` aborts via the agent's
 * internal ``AbortController`` and re-enables ``send``.
 */
export function useChatSession(
  agentName: string,
  options: UseChatSessionOptions = {},
): ChatSessionApi {
  const { threadId, initialMessages } = options;
  const accessToken = useAuthStore((s) => s.accessToken);
  const qc = useQueryClient();

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [status, setStatus] = useState<ChatStatus>('idle');
  const [error, setError] = useState<string | null>(null);
  // R7.1#3 follow-up — latest on_progress label from the agent. Last-wins
  // across parallel agents per the design call. Cleared on RunFinalized /
  // RunError so the strip disappears the moment the run settles.
  const [progressLabel, setProgressLabel] = useState<string | null>(null);

  // toolCallId → ChatToolCall, accumulated across the run so partial-args
  // events can update the right call regardless of arrival interleaving.
  const toolCallsRef = useRef<Map<string, ChatToolCall>>(new Map());

  // R4 #1 regen-with-model: when `sendWithModel` runs, it mutates
  // `agent.url` to include `?user_model_id=<id>` so the pragna route
  // routes this single run through the override model. The original
  // URL is captured here and restored in onRunFinalized so the next
  // plain `send` reverts to the conversation's persisted preference.
  const overrideUrlRef = useRef<string | null>(null);

  const agent = useMemo<HttpAgent | null>(() => {
    if (!accessToken) return null;
    return new HttpAgent({
      url: `${PRAGNA_BASE_URL}/agents/${encodeURIComponent(agentName)}`,
      headers: { Authorization: `Bearer ${accessToken}` },
      threadId,
      initialMessages,
    });
    // initialMessages is intentionally excluded from deps — it's a hydration
    // seed that should only matter when threadId changes. Including it would
    // re-create the agent (and reset state) every time a parent re-rendered
    // with a new array reference for the same history.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accessToken, agentName, threadId]);

  // Sync agent.messages → React state. Called from every relevant subscriber
  // callback so the UI is always a snapshot of the canonical AbstractAgent
  // state. Calling setMessages with a fresh array reference forces a
  // re-render; React bails out internally if shallow contents match.
  const syncMessages = useCallback(() => {
    if (!agent) return;
    const mirrored = agent.messages.map((m: Message) => toChatMessage(m, toolCallsRef.current));
    setMessages(mirrored);
  }, [agent]);

  useEffect(() => {
    if (!agent) return undefined;
    toolCallsRef.current = new Map();
    setStatus('idle');
    setError(null);
    // Hydrate React state from the agent's seed history. For a brand-new
    // chat ``agent.messages`` is empty so this resolves to ``[]``; for a
    // resumed chat it contains the messages we passed in via
    // ``initialMessages``, which would otherwise stay invisible until the
    // user typed something (subscriber callbacks only fire during a live
    // run, never for the seed). Without this call, clicking a recent
    // conversation in the sidebar produced a blank chat surface.
    syncMessages();

    const subscriber: AgentSubscriber = {
      onRunInitialized: () => {
        setStatus('running');
        setError(null);
        // R7.1#3 — reset on every new run so the strip starts fresh,
        // not carrying the last label from the prior turn.
        setProgressLabel(null);
      },
      onRunFailed: ({ error: e }) => {
        setStatus('error');
        setError(e.message || 'Run failed');
        // R7.1#3 — strip disappears on terminal state per the design
        // call (no "Stopping..." beat, matches ChatGPT/Claude.ai).
        setProgressLabel(null);
        logger.fromError('CHT_004:run_failed', e);
      },
      onRunFinalized: () => {
        setStatus((prev) => (prev === 'error' ? prev : 'idle'));
        setProgressLabel(null);
        // Restore the agent URL after a regen-with-model run so the
        // next plain `send` reverts to the conversation's persisted
        // user_model_id (the per-turn override is exactly that —
        // per-turn, never sticky).
        if (overrideUrlRef.current !== null && agent) {
          agent.url = overrideUrlRef.current;
          overrideUrlRef.current = null;
        }
        // First invalidation: catches the new conversation row that the
        // backend auto-created on first turn so it appears in the sidebar
        // immediately (title may still be null at this point).
        qc.invalidateQueries({ queryKey: ['conversations'] });
        // R4 #0: refetch the persisted message log for this conversation
        // so each assistant turn picks up its `user_model_id` attribution.
        // Mid-stream messages render with the conversation's preferred
        // model as a fallback; this invalidation upgrades them to the
        // authoritative server-stamped value (which matters when the
        // user used a per-turn ?user_model_id override).
        if (threadId) {
          qc.invalidateQueries({
            queryKey: ['conversations', threadId, 'messages'],
          });
        }
        // Second invalidation: rides past the backend's fire-and-forget
        // auto-title flow so the sidebar refreshes once the title is in
        // place. Cheap query; the cost is one extra request per turn.
        const timer = window.setTimeout(() => {
          qc.invalidateQueries({ queryKey: ['conversations'] });
        }, AUTO_TITLE_REFRESH_DELAY_MS);
        // No cleanup needed: setTimeout fires once, and on unmount the
        // subscriber is detached so this branch can still run safely.
        void timer;
      },
      onTextMessageStartEvent: () => {
        syncMessages();
      },
      onTextMessageContentEvent: () => {
        syncMessages();
      },
      onTextMessageEndEvent: () => {
        syncMessages();
      },
      onToolCallStartEvent: ({ event }) => {
        toolCallsRef.current.set(event.toolCallId, {
          id: event.toolCallId,
          name: event.toolCallName,
          argsBuffer: '',
          complete: false,
        });
        syncMessages();
      },
      onToolCallArgsEvent: ({ event, toolCallBuffer, partialToolCallArgs }) => {
        const existing = toolCallsRef.current.get(event.toolCallId);
        if (existing) {
          toolCallsRef.current.set(event.toolCallId, {
            ...existing,
            argsBuffer: toolCallBuffer,
            args: partialToolCallArgs as Record<string, unknown>,
          });
          syncMessages();
        }
      },
      onToolCallEndEvent: ({ event, toolCallArgs }) => {
        const existing = toolCallsRef.current.get(event.toolCallId);
        if (existing) {
          toolCallsRef.current.set(event.toolCallId, {
            ...existing,
            args: toolCallArgs as Record<string, unknown>,
            complete: true,
          });
          syncMessages();
        }
      },
      onToolCallResultEvent: ({ event }) => {
        const existing = toolCallsRef.current.get(event.toolCallId);
        if (existing) {
          toolCallsRef.current.set(event.toolCallId, {
            ...existing,
            result: event.content ?? '',
          });
        }
        syncMessages();
      },
      // R7.1#3 follow-up — every BaseAgentNode.__call__ on the BE
      // dispatches a LangChain on_progress custom event with payload
      // {label, agent_name}. ag_ui_langgraph forwards it as an AG-UI
      // CustomEvent with the same name. Last-wins: the most recent
      // emit overwrites previous labels (parallel agents render as a
      // single "currently active" indicator, matching Cursor /
      // ChatGPT behaviour).
      //
      // Unknown custom events are ignored — keeps the door open for
      // future event names without forcing every consumer to be
      // exhaustive.
      onCustomEvent: ({ event }) => {
        if (event.name !== 'on_progress') return;
        const value = event.value as { label?: unknown } | null | undefined;
        const label =
          value && typeof value === 'object' && typeof value.label === 'string'
            ? value.label
            : null;
        if (label) setProgressLabel(label);
      },
    };

    const { unsubscribe } = agent.subscribe(subscriber);
    return () => {
      unsubscribe();
      agent.abortRun();
    };
  }, [agent, syncMessages, qc]);

  const send = useCallback(
    (text: string, attachmentIds?: string[]) => {
      const trimmed = text.trim();
      if (!agent || !trimmed) return;
      if (status === 'running') return;

      agent.messages.push({
        id: randomId(),
        role: 'user',
        content: trimmed,
      });
      syncMessages();

      // R5: when attachments are staged, ride them along via AG-UI's
      // forwardedProps side channel. The backend's pragna route reads
      // ``forwarded_props.attachment_ids`` and resolves / capability-
      // gates / injects multi-part content before invoking the LLM.
      const runParams =
        attachmentIds && attachmentIds.length > 0
          ? { forwardedProps: { attachment_ids: attachmentIds } }
          : {};

      agent.runAgent(runParams).catch((e: unknown) => {
        // runAgent rejects when the subscriber chain throws; the
        // onRunFailed handler already updated state in that case. Log
        // here for any unhandled rejection path.
        if (e instanceof Error && e.name === 'AbortError') return;
        logger.fromError(
          'CHT_004:run_rejected',
          e instanceof Error ? e : new Error(String(e)),
        );
      });
    },
    [agent, status, syncMessages],
  );

  const sendWithModel = useCallback(
    (text: string, userModelId: string) => {
      const trimmed = text.trim();
      if (!agent || !trimmed) return;
      if (status === 'running') return;
      // Capture the current URL so onRunFinalized can restore it. Then
      // mutate the agent's URL to carry the override for this single run.
      // HttpAgent reads `this.url` at fetch-issue time inside runAgent;
      // setting it before calling send (which calls runAgent) is enough.
      overrideUrlRef.current = agent.url;
      const base = agent.url.split('?')[0];
      agent.url = `${base}?user_model_id=${encodeURIComponent(userModelId)}`;
      send(text);
    },
    [agent, status, send],
  );

  const sendWithOverrides = useCallback(
    (
      text: string,
      opts: {
        attachmentIds?: string[];
        userModelId?: string;
        thinkingEnabled?: boolean;
      },
    ) => {
      const trimmed = text.trim();
      if (!agent || !trimmed) return;
      if (status === 'running') return;

      // Build query params from non-undefined opts. Either-or makes
      // ``thinking_enabled`` survive being set to ``false`` — we want
      // an explicit "off" to round-trip to the backend instead of
      // being dropped.
      const params = new URLSearchParams();
      if (opts.userModelId) {
        params.set('user_model_id', opts.userModelId);
      }
      if (opts.thinkingEnabled !== undefined) {
        params.set('thinking_enabled', String(opts.thinkingEnabled));
      }

      if (params.toString().length > 0) {
        overrideUrlRef.current = agent.url;
        const base = agent.url.split('?')[0];
        agent.url = `${base}?${params.toString()}`;
      }

      send(text, opts.attachmentIds);
    },
    [agent, status, send],
  );

  const stop = useCallback(() => {
    if (agent && status === 'running') {
      agent.abortRun();
      setStatus('idle');
      // R7.1#3 — clear immediately on stop. RunFinalized also clears,
      // but it can lag a few hundred ms behind abort; we want the
      // strip to disappear the instant the user clicks Stop.
      setProgressLabel(null);
    }
  }, [agent, status]);

  return {
    messages,
    status,
    error,
    progressLabel,
    send,
    sendWithModel,
    sendWithOverrides,
    stop,
  };
}

/**
 * Translate an ``HttpAgent.messages`` entry into the UI's :class:`ChatMessage`
 * shape, attaching any tool calls we've accumulated in the running map.
 */
function toChatMessage(
  m: Message,
  toolCalls: Map<string, ChatToolCall>,
): ChatMessage {
  if (m.role === 'assistant') {
    const calls = m.toolCalls
      ?.map((tc) => toolCalls.get(tc.id))
      .filter((tc): tc is ChatToolCall => Boolean(tc));
    return {
      id: m.id,
      role: 'assistant',
      content: m.content ?? '',
      toolCalls: calls && calls.length > 0 ? calls : undefined,
    };
  }
  if (m.role === 'tool') {
    return {
      id: m.id,
      role: 'tool',
      content: m.content ?? '',
    };
  }
  if (m.role === 'system' || m.role === 'developer') {
    return { id: m.id, role: 'system', content: m.content ?? '' };
  }
  return {
    id: m.id,
    role: 'user',
    content: typeof m.content === 'string' ? m.content : '',
  };
}

function randomId(): string {
  // ``crypto.randomUUID`` is on every modern browser and jsdom; the fallback
  // exists only to keep TypeScript happy in environments without it.
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID();
  }
  return `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}
